module.exports = {
    '上海'  : './provinces/31.json',
    '河北'  : './provinces/13.json',
    '山西'  : './provinces/14.json',
    '内蒙古': './provinces/15.json',
    '辽宁'  : './provinces/21.json',
    '吉林'  : './provinces/22.json',
    '黑龙江': './provinces/23.json',
    '江苏'  : './provinces/32.json',
    '浙江'  : './provinces/33.json',
    '安徽'  : './provinces/34.json',
    '福建'  : './provinces/35.json',
    '江西'  : './provinces/36.json',
    '山东'  : './provinces/37.json',
    '河南'  : './provinces/41.json',
    '湖北'  : './provinces/42.json',
    '湖南'  : './provinces/43.json',
    '广东'  : './provinces/44.json',
    '广西'  : './provinces/45.json',
    '海南'  : './provinces/46.json',
    '四川'  : './provinces/51.json',
    '贵州'  : './provinces/52.json',
    '云南'  : './provinces/53.json',
    '西藏'  : './provinces/54.json',
    '陕西'  : './provinces/61.json',
    '甘肃'  : './provinces/62.json',
    '青海'  : './provinces/63.json',
    '宁夏'  : './provinces/64.json',
    '新疆'  : './provinces/65.json',
    '北京'  : './provinces/11.json',
    '天津'  : './provinces/12.json',
    '重庆'  : './provinces/50.json',
    '台湾'  : './provinces/71.json',
    '香港'  : './provinces/81.json',
    '澳门'  : './provinces/82.json'
}
